import type { LumiAuthentication } from './auth'
import type { LumiServerDatabase } from './database'
import type { LumiServerPluginStatus } from './pluginRegistry'
import type { LumiServerResourceLease } from './resourceLeases'

import { Buffer } from 'node:buffer'
import { timingSafeEqual } from 'node:crypto'

import { H3, serve } from 'h3'

export interface LumiManagerApiOptions {
  database: LumiServerDatabase
  authentication: LumiAuthentication
  /** Independent bearer secret shared only with local Server Manager. */
  token: string
  /** @default 6131 */
  port?: number
  toolControl?: {
    statusesSnapshot: () => Array<{ name: string, state: string, toolCount: number, lastError?: string }>
    listResourceLeases: () => LumiServerResourceLease[]
    terminateResourceLease: (leaseId: string) => LumiServerResourceLease
  }
  pluginControl?: {
    statusesSnapshot: () => LumiServerPluginStatus[]
  }
  dataControl?: {
    vectorStatus: () => Record<string, unknown>
    enqueueVectorBackfill: () => Record<string, unknown>
    stageMigration: (migration: unknown) => Promise<Record<string, unknown>>
    commitMigration: (migrationId: string) => Promise<Record<string, unknown>>
    createBackup: () => Promise<Record<string, unknown>>
  }
  deviceControl?: {
    revokeDevice: (accountId: string, deviceId: string) => unknown
  }
}

export interface LumiManagerApi {
  app: H3
  start: () => Promise<void>
  stop: () => Promise<void>
}

/**
 * Creates the loopback-only, content-free Server Manager control plane.
 *
 * Use when:
 * - Server Manager needs health, account bootstrap, invitations, and counts
 * - Public chat/auth traffic must remain isolated from administration
 *
 * Expects:
 * - The listener remains hard-bound to 127.0.0.1
 * - The token is generated by Server Manager and never exposed to clients
 *
 * Returns:
 * - A separate local HTTP lifecycle with no private-content read endpoint
 */
export function createLumiManagerApi(options: LumiManagerApiOptions): LumiManagerApi {
  const token = requiredText(options.token, 'manager token', 512)
  if (Buffer.byteLength(token) < 32)
    throw new Error('Manager token must contain at least 32 bytes')
  const app = new H3()

  app.get('/health', event => authorized(event.req, token, () => ({
    status: 'ok',
    role: 'server-manager-api',
  })))
  app.get('/overview', event => authorized(event.req, token, () => options.database.managerOverview()))
  app.get('/users', event => authorized(event.req, token, () => ({
    users: options.database.listPeople().map(person => ({
      ...person,
      accountBound: options.database.accountForPerson(person.id) !== undefined,
    })),
  })))
  app.get('/devices', event => authorized(event.req, token, () => ({ devices: options.database.listDevices() })))
  app.post('/devices/revoke', event => authorized(event.req, token, async () => {
    const body = await jsonRecord(event.req)
    return options.deviceControl?.revokeDevice(
      requiredText(body.accountId, 'accountId', 160),
      requiredText(body.deviceId, 'deviceId', 160),
    ) ?? options.database.revokeDevice(
      requiredText(body.accountId, 'accountId', 160),
      requiredText(body.deviceId, 'deviceId', 160),
    )
  }))
  app.get('/tools/status', event => authorized(event.req, token, () => ({
    servers: options.toolControl?.statusesSnapshot() ?? [],
    activeResourceLeases: options.toolControl?.listResourceLeases() ?? [],
  })))
  app.get('/plugins/status', event => authorized(event.req, token, () => ({
    plugins: options.pluginControl?.statusesSnapshot() ?? [],
  })))
  app.post('/tools/resource-leases/terminate', event => authorized(event.req, token, async () => {
    if (!options.toolControl)
      throw new Error('Server tool control is not configured')
    const body = await jsonRecord(event.req)
    return options.toolControl.terminateResourceLease(requiredText(body.leaseId, 'leaseId', 160))
  }))
  app.get('/memory/vector/status', event => authorized(event.req, token, () => options.dataControl?.vectorStatus() ?? { enabled: false }))
  app.post('/memory/vector/backfill', event => authorized(event.req, token, () => {
    if (!options.dataControl)
      throw new Error('Server data control is not configured')
    return options.dataControl.enqueueVectorBackfill()
  }))
  app.post('/data/migrations/stage', event => authorized(event.req, token, async () => {
    if (!options.dataControl)
      throw new Error('Server data control is not configured')
    return await options.dataControl.stageMigration(await event.req.json())
  }))
  app.post('/data/migrations/commit', event => authorized(event.req, token, async () => {
    if (!options.dataControl)
      throw new Error('Server data control is not configured')
    const body = await jsonRecord(event.req)
    return await options.dataControl.commitMigration(requiredText(body.migrationId, 'migrationId', 160))
  }))
  app.post('/data/backups', event => authorized(event.req, token, async () => {
    if (!options.dataControl)
      throw new Error('Server data control is not configured')
    return await options.dataControl.createBackup()
  }))
  app.post('/bootstrap/doggy', event => authorized(event.req, token, async () => {
    const body = await jsonRecord(event.req)
    return options.authentication.bootstrapDoggy({
      username: requiredText(body.username, 'username', 64),
      password: requiredText(body.password, 'password', 128),
    })
  }))
  app.post('/invitations', event => authorized(event.req, token, async () => {
    const body = await jsonRecord(event.req)
    return options.database.createInvitation(
      requiredText(body.personId, 'personId', 160),
      optionalPositiveInteger(body.expiresInMs),
    )
  }))

  let listener: ReturnType<typeof serve> | undefined
  return {
    app,
    async start() {
      if (listener)
        return
      listener = serve(app, {
        hostname: '127.0.0.1',
        port: options.port ?? 6_131,
        manual: true,
        silent: true,
        gracefulShutdown: false,
      })
      await listener.serve()
    },
    async stop() {
      await listener?.close(true)
      listener = undefined
    },
  }
}

function authorized<TResult>(request: Request, expectedToken: string, operation: () => TResult): TResult | Response {
  const authorization = request.headers.get('authorization') ?? ''
  const supplied = authorization.startsWith('Bearer ') ? authorization.slice(7) : ''
  if (!constantTimeEqual(supplied, expectedToken))
    return Response.json({ error: 'Manager authorization required' }, { status: 401 })
  return operation()
}

async function jsonRecord(request: Request): Promise<Record<string, unknown>> {
  const value: unknown = await request.json()
  if (!value || typeof value !== 'object' || Array.isArray(value))
    throw new Error('JSON object body required')
  return value as Record<string, unknown>
}

function optionalPositiveInteger(value: unknown) {
  if (value === undefined)
    return undefined
  if (!Number.isInteger(value) || Number(value) < 1)
    throw new Error('expiresInMs must be a positive integer')
  return Number(value)
}

function requiredText(value: unknown, field: string, maxLength: number) {
  const normalized = typeof value === 'string' ? value.trim() : ''
  if (!normalized)
    throw new Error(`${field} is required`)
  if (normalized.length > maxLength)
    throw new Error(`${field} is too long`)
  return normalized
}

function constantTimeEqual(left: string, right: string) {
  const leftBuffer = Buffer.from(left)
  const rightBuffer = Buffer.from(right)
  return leftBuffer.length === rightBuffer.length && timingSafeEqual(leftBuffer, rightBuffer)
}
